### ISSUE TITLE
[Bug]:  Defooocus google colab version suddenly today disturbed not working when run the cell it break with error SEE in description plz correct it

### ISSUE THREAD

**Issue by mhsin321** [ehristoforu/DeFooocus#24]
### Prerequisites

- [X] I have read the [Troubleshooting Guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [x] I have checked that this is not a duplicate of an already existing [issue](https://github.com/lllyasviel/Fooocus/issues)

### Describe the problem

[DeFooocus] Preparing ...
/content
fatal: destination path 'DeFooocus' already exists and is not an empty directory.
/content/DeFooocus
WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl (from -r requirements_versions.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5
[DeFooocus] Starting ...
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--attention-split', '--always-high-vram', '--disable-offload-from-vram', '--all-in-fp16', '--theme', 'dark']
Python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
Fooocus version: 0.2
Error checking version for torchsde: No package metadata was found for torchsde
Installing requirements
Couldn't install requirements.
Command: "/usr/bin/python3" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Collecting torchsde==0.2.5 (from -r requirements_versions.txt (line 1))
  Using cached torchsde-0.2.5-py3-none-any.whl.metadata (748 bytes)

stderr: WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl (from -r requirements_versions.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5

CMD Failed requirements: install -r "requirements_versions.txt"
Traceback (most recent call last):
  File "/content/DeFooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/DeFooocus/launch.py", line 128, in <module>
    from webui import *
  File "/content/DeFooocus/webui.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Full console log output

```shell
[DeFooocus] Preparing ...
/content
fatal: destination path 'DeFooocus' already exists and is not an empty directory.
/content/DeFooocus
WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl (from -r requirements_versions.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5
[DeFooocus] Starting ...
Already up-to-date
Update succeeded.
[System ARGV] ['entry_with_update.py', '--share', '--attention-split', '--always-high-vram', '--disable-offload-from-vram', '--all-in-fp16', '--theme', 'dark']
Python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
Fooocus version: 0.2
Error checking version for torchsde: No package metadata was found for torchsde
Installing requirements
Couldn't install requirements.
Command: "/usr/bin/python3" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Collecting torchsde==0.2.5 (from -r requirements_versions.txt (line 1))
  Using cached torchsde-0.2.5-py3-none-any.whl.metadata (748 bytes)

stderr: WARNING: Ignoring version 0.2.5 of torchsde since it has invalid metadata:
Requested torchsde==0.2.5 from https://files.pythonhosted.org/packages/73/8d/efd3e7b31ea854d0bd6886aa3cf44914adce113a6d460850af41ac1dd4dd/torchsde-0.2.5-py3-none-any.whl (from -r requirements_versions.txt (line 1)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement torchsde==0.2.5 (from versions: 0.2.5, 0.2.6)
ERROR: No matching distribution found for torchsde==0.2.5

CMD Failed requirements: install -r "requirements_versions.txt"
Traceback (most recent call last):
  File "/content/DeFooocus/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/DeFooocus/launch.py", line 128, in <module>
    from webui import *
  File "/content/DeFooocus/webui.py", line 1, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```


### Version

latest version on google colab

### Where are you running Fooocus?

Cloud (Gradio)

### Operating System

windows 11

### What browsers are you seeing the problem on?

Chrome

**Comment by rawwwww** [comment]
same issue

**Comment by mhsin321** [comment]
> same issue

yeah and that happening today 1 day before it was good also did someone knows how to use install SD3 and other Cevitia models inside of this colab Defooocus ??

**Comment by ehristoforu** [comment]
Sorry for the inconvenience, everything is fixed)

**Comment by mhsin321** [comment]
> Sorry for the inconvenience, everything is fixed)

oh tnx tnx tnx you came like massiah I love to use Defooocus but sad for yesterday ... ]
but hey you did not also solve another our big problem plz -lz p[lz solve it. Otherwise its make us disheartened to use it your defooocus more and that is
plz add more many models amazi ng in defooocus you did not made any tutorials nor we know how to do it by ourself in google colab version only plz will you add SD3 in colab version plzz ASAP?!

**Comment by mhsin321** [comment]
ANd heeeey why i cant see FOOOCUS version 2.5.1 the latest one in it which was I used before in Defooocus of yours WTH why everything messed ??

**Comment by ehristoforu** [comment]
Hmmm... DeFooocus was always an older version, soon we will update to 2.5.1 and above)

**Comment by ehristoforu** [comment]
> oh tnx tnx tnx you came like massiah I love to use Defooocus but sad for yesterday ... ] but hey you did not also solve another our big problem plz -lz p[lz solve it. Otherwise its make us disheartened to use it your defooocus more and that is plz add more many models amazi ng in defooocus you did not made any tutorials nor we know how to do it by ourself in google colab version only plz will you add SD3 in colab version plzz ASAP?!

Adding SD3 support is a bit complicated and I don't think it's entirely appropriate yet, DeFooocus and Fooocus use the LM model to improve the promt, most likely it was trained for SDXL, not SD3, time will tell, if it's necessary we'll certainly do it)

**Comment by mhsin321** [comment]
> > oh tnx tnx tnx you came like massiah I love to use Defooocus but sad for yesterday ... ] but hey you did not also solve another our big problem plz -lz p[lz solve it. Otherwise its make us disheartened to use it your defooocus more and that is plz add more many models amazi ng in defooocus you did not made any tutorials nor we know how to do it by ourself in google colab version only plz will you add SD3 in colab version plzz ASAP?!
> 
> Adding SD3 support is a bit complicated and I don't think it's entirely appropriate yet, DeFooocus and Fooocus use the LM model to improve the promt, most likely it was trained for SDXL, not SD3, time will tell, if it's necessary we'll certainly do it)

oh come on don't be so silly come on where is ur brain maan SD# is not necessarily for your perspective come on whole world mad for it even SD3 can generate text too which I mostly love in any effect after all u gyz think its not imp. very bad
plz its all of us demanding to put SD3 
also why cant you put more many models in model category of sdxl like epic erealism and many more which original fooocus has we get only one stupid model always hmmm
and no some days before I used fooocus 2.5.1 in under this defooocus then its go buggy why we want at least you gyz allow in today for defooocus to use 2.5.1 fooocus ASAP!? @_@
tnx

**Comment by mhsin321** [comment]
> > oh tnx tnx tnx you came like massiah I love to use Defooocus but sad for yesterday ... ] but hey you did not also solve another our big problem plz -lz p[lz solve it. Otherwise its make us disheartened to use it your defooocus more and that is plz add more many models amazi ng in defooocus you did not made any tutorials nor we know how to do it by ourself in google colab version only plz will you add SD3 in colab version plzz ASAP?!
> 
> Adding SD3 support is a bit complicated and I don't think it's entirely appropriate yet, DeFooocus and Fooocus use the LM model to improve the promt, most likely it was trained for SDXL, not SD3, time will tell, if it's necessary we'll certainly do it)

???

**Comment by mhsin321** [comment]
> Sorry for the inconvenience, everything is fixed)

pzl reply

**Comment by ehristoforu** [comment]
> pzl reply

Hello again, adding SD3 is not planned yet, it does not surpass SDXL and SD1.5 objectively, the trick with the text is not a reason to abandon SDXL models, in SD3 StabilityAI they used completely censored datasets, thus they not only killed NSFW but also killed anatomy, if you do not understand how this is connected, then read about Diffusion models or trust me (I develop models myself and know what it is), SD3 also behaves poorly with the GPT2 model of Fooocus, it needs a different type of promting, and GPT2 has already been trained on SD1.5 and SDXL promting.

**Comment by mhsin321** [comment]
read my all Q....
